version: "3.9"
services:
  # web:

  #   depends_on:
  #     - postgres_db

  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile

  #   image: django-k8s:v1 # any image name can be given

  #   environment:
  #     - PORT=8020

  #   env_file:
  #     - web/.env

  #   ports:
  #     - "8001:8020" # 8001 is localport, 8020 is internal running port

  #   command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh" # we want run addn cmd or change default cmd for dockerfile

  #   volumes:
  #      - staticfiles:/app/staticfiles/

  mysql_db:
    image: mysql
    restart: always
    command: -p 5434
    env_file:
     - web/.env
    expose:
     - 5434
    ports:
     - "5434:5434" # to expose the same port say 5433 on then add as cmd
    volumes: # for persistent data in postgr db
     - mysql_data:/var/lib/mysql/data/

  redis_db:
      image: redis
      restart: always
      expose:
        - 6388
      ports:
        - "6388:6388"
      volumes:
          - redis_data:/data
      entrypoint: redis-server --appendonly yes --port 6388

volumes:
  #staticfiles:
   #   external: true
  mysql_data:
  redis_data: